### ISSUE TITLE
能成功启动服务，admin登录功能点不全，报表功能无法使用

### ISSUE THREAD

**Issue by CoolChenGod** [ruisibi/rsbi-pom#5]
请问开源版中提及的还原数据库“rs_report_data.bak”这个文件是没有的，压缩包中只有“rs_report.bak”，成功启动服务后，admin账户登录功能点显示不全，新建报表页面也报错，是因为库数据的问题吗

**Comment by ruisibi** [comment]
开源版功能比标准版少，演示系统是标准版。
