### ISSUE TITLE
postgresql数据库非public schema的表建模报错 

### ISSUE THREAD

**Issue by zixuedanxin** [ruisibi/rsbi-pom#8]
postgresql数据库非public schema的表建模报错。找不到表。应该是没有指定schema的问题。这个改怎么解决

**Comment by SeanYanxml** [comment]
> postgresql数据库非public schema的表建模报错。找不到表。应该是没有指定schema的问题。这个改怎么解决

你好. 我是你fork的仓库bigdata的作者. 因为某些原因, 我想删除所有的fork仓库. 因为github的策略, 您的仓库变成了第一个仓库(您暂时先别删除仓库). 能否请您帮我个忙. 我的邮箱是huaianyanxu@163.com . 麻烦了, 等待您的消息.

**Comment by SeanYanxml** [comment]
> postgresql数据库非public schema的表建模报错。找不到表。应该是没有指定schema的问题。这个改怎么解决

请本项目的作者手下留情, 联系上@zixuedanxin 后我会自删. 另外, @zixuedanxin 还请先别删除您fork的bigdata仓库, 相关操作我会联系您, 事后有补偿奉上.

**Comment by ruisibi** [comment]
已解决
